using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Class required to communicate with machine learning module.
/// </summary>
public class MLCommunicator {

    /// <summary>
    /// reads parameter tuning data file generated by machine learning module
    /// </summary>
    public static void readMLFile() {

        //TODO:Implement
        return;
    }

    /// <summary>
    /// writes level stats to a file to be used by machine learning module
    /// </summary>
    /// <param name="levelStats">LevelStats of current level</param>
    public static void writeMLFile( MLLevelStats levelStats) {

        //TODO:Implement
        return;
    }
}
